language: java

jdk:
  - oraclejdk8
  - openjdk8

script:
  - gradle test

env:
- TERM=dumb

after_success:
- gradle jacocoTestReport coveralls

notifications:
  slack:
    secure: fK3kbDHg/kwFCjxhFkg0wkOcwXoFwkfJJdRFwZQtnMDkY4yHNtr9SWIHWOiI9OceNgWLeHwvvm/7737WBWnTf4RF3mn0/D9xYtOn+DfV2gb1xXVjDb33oBQWrFN8P1x4xFNOMw38LQ46NYvsv6bfPmZRJpKuvHPVJUsBCINx14w=
