language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  except: updates-hack-for-demo


script:
  - jdk_switcher use oraclejdk8
  - gradle test
  - jdk_switcher use oraclejdk7
  - gradle test
  - jdk_switcher use openjdk7
  - gradle test
  - jdk_switcher use openjdk6
  - gradle test

env:
- TERM=dumb

after_success:
- gradle jacocoTestReport coveralls

notifications:
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never
