language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - gradle test

env:
- TERM=dumb

after_success:
- gradle jacocoTestReport coveralls

notifications:
  slack: seek4science:Jds9srWlt27UZUoD3MnJoUWb
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never
